- src/views/resource/cluster/components/UpdateCluster.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix(ui): 修复编辑集群无法展示镜像bug

- src/views/resource/ingress/components/ResourceInfo.vue
- src/views/resource/ingress/detail.vue
Fixes #
Reference to #
/cc @chenshunliang 
```release-note
NONE
```
> 🐞 fix(ingress): find gateway and get port error

- README.md
- yarn.lock
update readme.md
Fixes #
Reference to #
```release-note
NONE
```
> docs(docs): 📝  update readme.md

- src/views/observe/metrics/targets/components/TargetsForm.vue
- src/views/resource/ingress/index.vue
Fixes #
Reference to #
/cc @chenshunliang 
```release-note
NONE
```
> fix some bugs

- src/views/resource/cluster/components/AddCluster.vue
- src/views/resource/cluster/index.vue
- src/views/resource/prometheusrule/components/PrometheusRuleBaseForm/Rule/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix(ui): 🐛  fix prometheus rule create bug

- src/views/resource/environment/components/base/LimitRangeCard.vue
- src/views/resource/registry/components/RegistryBaseForm.vue
- src/views/resource/registry/index.vue
- yarn.lock
Fixes #
Reference to #
```release-note
NONE
```
> docs(ui): 📝 update text

- src/assets/styles/vuetify_overwrite.scss
- src/views/microservice/virtualspace/components/UpdateVirtualSpace.vue
- src/views/microservice/virtualspace/components/VirtualSpaceBaseForm/LinkEnvironment/EnvironmentItem.vue
- src/views/microservice/virtualspace/components/VirtualSpaceBaseForm/LinkEnvironment/index.vue
- src/views/microservice/virtualspace/components/VirtualSpaceBaseForm/index.vue
- src/views/resource/dashboard/components/ProjectList/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix(ui): 🐛  修复虚拟空间无法删除环境bug

- src/views/observe/metrics/targets/components/TargetsEndpointsItem.vue
Fixes #
Reference to #
```release-note
NONE
```
> 拉取间隔 -> 采集间隔

- src/views/microservice/service/index.vue
- src/views/microservice/workload/index.vue
- src/views/tenant/user/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix(ui): 🐛  修复微服务下服务与负载注入标签漂移问题

- src/views/observe/log/viewer/components/LogQuery/index.vue
- src/views/observe/log/viewer/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix(ui): 🐛  修复日志时间戳无法匹配时间组件问题

- src/views/observe/log/viewer/components/LogLevelSelector.vue
- src/views/observe/log/viewer/components/LogQuery/LabelSelector/index.vue
- src/views/observe/log/viewer/components/LogQuery/index.vue
- src/views/observe/log/viewer/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix(ui): 🐛  修复日志级别过滤debug状态失效问题

- src/views/observe/log/viewer/components/LogQuery/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix(ui): 🐛  修复刷新浏览器日志选中标签丢失问题

- .github/workflows/build.yml
Fixes #
Reference to #
```release-note
NONE
```
> refactor(ui): 🔨  update build.yml,modify pull_request conf

- src/api/resource/select.js
- src/api/tenant/select.js
- src/mixins/select.js
- src/router/admin_observe.js
- src/router/observe.js
- src/views/observe/log/viewer/components/LogQuery/LabelSelector/index.vue
- src/views/observe/log/viewer/components/LogQuery/ProjectEnvSelect.vue
- src/views/observe/log/viewer/components/LogQuery/index.vue
- src/views/observe/log/viewer/components/LogQueryHistory.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix(ui): 🐛  log viewer labels {project,environment}=>{namespace}

- .stylelintrc.js
- README.md
- package.json
- src/layouts/Layout.vue
- src/layouts/header/Message.vue
- src/layouts/sidebar/Sidebar.vue
- src/views/observe/integrated/components/IntergatedCenter/Logging.vue
- yarn.lock
Fixes #
Reference to #
```release-note
NONE
```
> refactor: 🔨  upgrade vuetify 2.6.1 => 2.6.5

- src/utils/prometheus.js
- src/views/observe/monitor/overview/index.vue
- src/views/observe/overview/components/OverviewList/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix apiserver qps and alert dashboard 

- .github/workflows/build.yml
- src/views/resource/app/index.vue
- src/views/resource/deploy/components/DeployStatus/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: 🐛  fix app runtime status not complete bug

- src/mixins/resource.js
- src/views/resource/prometheusrule/components/PrometheusRuleBaseForm/Rule/index.vue
- src/views/resource/workload/components/WorkloadBaseForm/StorageMount/index.vue
- src/views/resource/workload/components/WorkloadBaseForm/StorageMount/volume_section/ConfigMapMount.vue
- src/views/resource/workload/components/WorkloadBaseForm/StorageMount/volume_section/EmptyDirMount.vue
- src/views/resource/workload/components/WorkloadBaseForm/StorageMount/volume_section/PersistentVolumeClaimMount.vue
- src/views/resource/workload/components/WorkloadBaseForm/StorageMount/volume_section/SecretMount.vue
Fixes #
Reference to #
```release-note
NONE
```
> feat: 🌟  support emptyDir volume mount

- src/mixins/resource.js
- src/views/resource/workload/components/WorkloadBaseForm/StorageMount/StorageMountItem.vue
- src/views/resource/workload/components/WorkloadBaseForm/StorageMount/volume_section/PersistentVolumeClaimMount.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: 🐛  fix form data spaces appear in quotes when converting yaml

- src/components/BaseConfirm.vue
- src/mixins/table.js
Fixes #
Reference to #
```release-note
NONE
```
> perf: 🚀  optimization batch delete resources tips

- src/assets/styles/common.scss
- src/views/resource/pod/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> style: 🎨  set pod list table css cursor:pointer

- src/views/resource/node/components/ResourceInfo.vue
- src/views/resource/node/detail.vue
- src/views/resource/node/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> style: 🎨  optimization node detail gpu charts

- src/components/BaseClusterHeader.vue
- src/components/BaseMicroServiceHeader.vue
- src/components/BaseTenantHeader.vue
Fixes #
Reference to #
```release-note
NONE
```
> perf: 🚀  optimization base header switch speed

- nginx.conf.template
Fixes #
Reference to #
```release-note
NONE
```
> fix: 🐛  fix nginx location cached proxy service static resources

- src/views/resource/workload/components/WorkloadBaseForm/ContainerImage/ContainerImageItem.vue
- src/views/resource/workload/components/WorkloadBaseForm/ContainerImage/ContainerImageSelect.vue
- src/views/resource/workload/components/WorkloadBaseForm/StorageMount/StorageMountItem.vue
- src/views/resource/workload/components/WorkloadBaseForm/StorageMount/index.vue
- src/views/resource/workload/components/WorkloadBaseForm/StorageMount/volume_section/ConfigMapMount.vue
- src/views/resource/workload/components/WorkloadBaseForm/StorageMount/volume_section/EmptyDirMount.vue
- src/views/resource/workload/components/WorkloadBaseForm/StorageMount/volume_section/HostPathMount.vue
- src/views/resource/workload/components/WorkloadBaseForm/StorageMount/volume_section/PersistentVolumeClaimMount.vue
- src/views/resource/workload/components/WorkloadBaseForm/StorageMount/volume_section/SecretMount.vue
- src/views/resource/workload/components/WorkloadBaseForm/StorageMount/volume_section/VolumeMountForInitContainer.vue
Fixes #
Reference to #
```release-note
NONE
```
> perf: 🚑 support initcontainer volume mount

- src/views/tool/audit/index.vue
- src/views/tool/event/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: 🐛  fix audit and event time not refresh

- src/api/system/config.js
- src/utils/namespace.js
Fixes #
Reference to #
```release-note
NONE
```
> change some const and url

- src/views/resource/service/components/AddService.vue
- src/views/resource/service/components/ServiceBaseForm/index.vue
- src/views/resource/service/components/UpdateService.vue
- src/views/resource/service/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> perf: 🚀 support svc externalip and externalname

- src/views/appstore/components/StatusTip.vue
- src/views/appstore/list.vue
- src/views/resource/app/components/AppStatusTip.vue
- src/views/resource/app/components/TaskStatusTip.vue
- src/views/resource/app/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> perf: 🚀  optimization registry status error message

- src/views/observe/integrated/components/IntergatedCenter/Logging.vue
Fixes #
Reference to #
```release-note
NONE
```
> 🐞 fix(log metric): app name-label map

- src/views/resource/service/components/ServiceBaseForm/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: 🐛  fix service label selector related workload

- src/views/resource/service/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> perf: 🚀  optimization service externalip and loadbalancerip  list

- src/views/microservice/app/index.vue
- src/views/microservice/components/InboundTrafficIframe.vue
- src/views/microservice/components/NetworkTopologyIframe.vue
- src/views/microservice/components/OutboundTrafficIframe.vue
- src/views/resource/deploy/components/DeployControlCenter/DeployStepPanel.vue
Enable Kiali hashmode url, to avoid crack on kiali server.
> [Perf]switch to kiali hash mode

- src/components/BaseCollapseChips.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: 🐛  fix svc port menu click content closed occured copy filed

- src/api/metrics/prometheusrule.js
- src/api/metrics/receiver.js
- src/api/system/config.js
- src/views/observe/log/config/alert_rule/index.vue
- src/views/observe/log/config/receiver/index.vue
- src/views/observe/monitor/config/prometheusrule/components/AddPrometheusRule.vue
- src/views/observe/monitor/config/prometheusrule/index.vue
- src/views/observe/monitor/config/receiver/components/AddReceiver.vue
- src/views/observe/monitor/config/receiver/components/UpdateReceiver.vue
- src/views/observe/monitor/config/receiver/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> refactor(monitor): alert and receiver add source

- .eslintrc.js
- src/api/metrics/prometheusrule.js
- src/api/metrics/receiver.js
- src/api/system/config.js
- src/views/observe/log/config/alert_rule/index.vue
- src/views/observe/log/config/receiver/index.vue
- src/views/observe/monitor/config/prometheusrule/components/AddPrometheusRule.vue
- src/views/observe/monitor/config/prometheusrule/index.vue
- src/views/observe/monitor/config/receiver/components/AddReceiver.vue
- src/views/observe/monitor/config/receiver/components/UpdateReceiver.vue
- src/views/observe/monitor/config/receiver/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> perf: :art: code formatter

- src/components/BaseApexAreaChart.vue
- src/mixins/resource.js
- src/views/observe/log/config/alert_rule/index.vue
- src/views/observe/log/config/receiver/index.vue
- src/views/observe/monitor/config/prometheusrule/index.vue
- src/views/observe/monitor/config/receiver/index.vue
- src/views/observe/monitor/config/servicemonitor/index.vue
- src/views/resource/environment/components/EnvironmentBaseForm/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix add environment resourcequota no data bug

- src/views/resource/configmap/mixins/schema.js
Fixes #
Reference to #
```release-note
NONE
```
> fix: 🐛  fix configmap yaml commit binaryData error bug

- .eslintrc.js
- src/App.vue
- src/layouts/header/Message.vue
- src/mixins/resource.js
- src/views/resource/configmap/mixins/schema.js
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix configmap binaryData yaml commit error bug

- src/utils/prometheus.js
Fixes #
Reference to #
```release-note
NONE
```
> 🐞 fix(promql): label host -> node

- src/components/BaseApexAreaChart.vue
- src/views/resource/node/components/NodeMonitor.vue
- src/views/resource/node/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> 🐞 fix(node monitor): fix node label and BaseApexAreaChart label priority

- src/views/observe/overview/components/OverviewList/K8sEvents/index.vue
- src/views/resource/dashboard/components/EventList.vue
- src/views/tool/event/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> 🐞 fix(event): container gems-eventer -> event-exporter

- src/views/resource/appmanifest/components/AppResourceFileList/AddResourceFile.vue
- src/views/resource/appmanifest/components/AppResourceFileList/UpdateResourceFile.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix add appmanifest yaml schema error bug

- src/store/index.js
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix global plugins pass error when multiple clusters

- src/components/BaseApexAreaChart.vue
Fixes #
Reference to #
```release-note
NONE
```
> style: :art: set stroke line width = 2

- src/utils/prometheus.js
- src/views/observe/log/viewer/components/LogTable/LogPodMonitor.vue
- src/views/observe/log/viewer/components/LogTable/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> perf: :ambulance: optimization log viewer pod monitor

- src/views/observe/log/config/alert_rule/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> 🐞 fix(log): delete log alert api error

- public/css/skeleton.css
- public/index.html
- src/main.js
- src/router/observe.js
- src/views/authentication/index.vue
- src/views/observe/integrated/components/IntergatedCenter/MiddlewareMetrics/index.vue
- src/views/observe/monitor/config/prometheusrule/components/PrometheusRuleBaseForm/Rule/index.vue
- src/views/observe/monitor/dashboard/components/GraphBaseForm.vue
- src/views/observe/monitor/dashboard/components/ProjectEnvSelect.vue
- src/views/observe/monitor/dashboard/index.vue
- src/views/observe/monitor/metrics/index.vue
- src/views/observe/overview/components/OverviewList/K8sEvents/Chart/EventPieChart.vue
- src/views/observe/overview/components/OverviewList/K8sEvents/Chart/MessageBarChart.vue
- src/views/observe/overview/components/OverviewList/K8sEvents/Chart/index.vue
- src/views/observe/overview/components/OverviewList/K8sEvents/EventList.vue
- src/views/observe/overview/components/OverviewList/K8sEvents/index.vue
- src/views/resource/dashboard/components/ProjectList/index.vue
- vue.config.js
Fixes #
Reference to #
```release-note
NONE
```
> feat: :sparkles: add skeleton flash, :bug: fix log rule create bug

- src/store/index.js
- src/views/observe/components/ProjectEnvironmentLayout.vue
- src/views/observe/log/config/alert_rule/detail.vue
- src/views/observe/monitor/config/prometheusrule/detail.vue
- src/views/observe/monitor/config/receiver/components/ReceiverBaseForm/ChannelForm/EmailForm.vue
- src/views/observe/overview/components/OverviewList/K8sEvents/EventList.vue
- src/views/observe/overview/components/OverviewList/K8sEvents/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix receiver email envid error

- src/utils/prometheus.js
- src/views/resource/cluster/components/MetricMonitor.vue
- src/views/resource/node/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix pod memory usage promql

- public/css/skeleton.css
- public/index.html
- src/main.js
- src/store/index.js
- src/views/authentication/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> style: :art: optimization login animation

- src/views/observe/alert/history/index.vue
- src/views/observe/monitor/config/prometheusrule/components/PrometheusRuleBaseForm/Rule/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> 🎈 perf(alert): log alert form and alert history

- src/views/observe/log/config/alert_rule/detail.vue
- src/views/observe/log/config/alert_rule/index.vue
- src/views/observe/monitor/config/prometheusrule/detail.vue
- src/views/observe/monitor/config/prometheusrule/index.vue
> 🐞 fix(alert): fix delete alert in detail and source error

- src/api/visualization/monitor.js
- src/views/observe/monitor/dashboard/components/DashboardBaseForm.vue
- src/views/observe/monitor/dashboard/components/UpdateDashboard.vue
Fixes #
Reference to #
```release-note
NONE
```
> perf: :ambulance: monitor dashboard add create from template

- src/utils/chart.js
- src/views/observe/log/viewer/components/LogTable/LogPodMonitor.vue
- src/views/observe/log/viewer/components/LogTable/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: fix log viewer chart timestamp not related bug

- src/views/resource/app_configer/components/ConfigEditor.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix nacos ace language switch duplicate bug

- src/views/authentication/index.vue
- src/views/observe/integrated/components/IntergatedCenter/MiddlewareMetrics/index.vue
- src/views/observe/monitor/dashboard/index.vue
- src/views/observe/monitor/metrics/components/MetricsItem.vue
- src/views/observe/monitor/metrics/index.vue
- src/views/observe/overview/components/OverviewList/index.vue
- src/views/resource/app_configer/components/ConfigEditor.vue
- src/views/resource/app_configer/components/ConfigSDK.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix few bugs

- public/css/skeleton.css
- src/assets/styles/common.scss
- src/views/authentication/index.vue
- src/views/resource/app_configer/components/ConfigEditor.vue
- src/views/resource/app_configer/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> 🎨  update skeleton animation-timing-function, 🚑 optimization nacos conf display

- src/components/BaseApexAreaChart.vue
- src/views/observe/alert/dashboard/components/AlertHistoryBar.vue
- src/views/observe/alert/dashboard/index.vue
- src/views/observe/monitor/dashboard/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> style: 💄 optimization monitor dashboard line colorful

- src/views/observe/overview/components/OverviewList/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix observe dashboard realtime alert error show bug

- src/views/observe/integrated/components/IntergatedCenter/Metrics/docs/cpp.mdx
- src/views/observe/integrated/components/IntergatedCenter/Metrics/docs/csharp.mdx
- src/views/observe/integrated/components/IntergatedCenter/Metrics/docs/erlang.mdx
- src/views/observe/integrated/components/IntergatedCenter/Metrics/docs/golang.mdx
- src/views/observe/integrated/components/IntergatedCenter/Metrics/docs/java.mdx
- src/views/observe/integrated/components/IntergatedCenter/Metrics/docs/javascript.mdx
- src/views/observe/integrated/components/IntergatedCenter/Metrics/docs/nodejs.mdx
- src/views/observe/integrated/components/IntergatedCenter/Metrics/docs/php.mdx
- src/views/observe/integrated/components/IntergatedCenter/Metrics/docs/python.mdx
- src/views/observe/integrated/components/IntergatedCenter/Metrics/docs/ruby.mdx
- src/views/observe/integrated/components/IntergatedCenter/Metrics/docs/rust.mdx
- src/views/observe/integrated/components/IntergatedCenter/Metrics/docs/swift.mdx
- src/views/observe/integrated/components/IntergatedCenter/Trace/docs/cpp.mdx
- src/views/observe/integrated/components/IntergatedCenter/Trace/docs/csharp.mdx
- src/views/observe/integrated/components/IntergatedCenter/Trace/docs/erlang.mdx
- src/views/observe/integrated/components/IntergatedCenter/Trace/docs/golang.mdx
- src/views/observe/integrated/components/IntergatedCenter/Trace/docs/java.mdx
- src/views/observe/integrated/components/IntergatedCenter/Trace/docs/javascript.mdx
- src/views/observe/integrated/components/IntergatedCenter/Trace/docs/nodejs.mdx
- src/views/observe/integrated/components/IntergatedCenter/Trace/docs/php.mdx
- src/views/observe/integrated/components/IntergatedCenter/Trace/docs/python.mdx
- src/views/observe/integrated/components/IntergatedCenter/Trace/docs/ruby.mdx
- src/views/observe/integrated/components/IntergatedCenter/Trace/docs/rust.mdx
- src/views/observe/integrated/components/IntergatedCenter/Trace/docs/swift.mdx
- src/views/observe/overview/components/OverviewList/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> :memo: update trace and metrics docs

- src/views/observe/components/ProjectEnvSelectCascade.vue
- src/views/observe/monitor/dashboard/index.vue
- src/views/observe/monitor/metrics/components/ResourceSelectCascade.vue
- src/views/observe/monitor/metrics/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> perf: :ambulance: optimization resouce template selector

- src/views/observe/monitor/metrics/components/ResourceSelectCascade.vue
- src/views/observe/monitor/metrics/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix monitor dashboard cluster change data error bug

- package.json
- yarn.lock
Fixes #
Reference to #
```release-note
NONE
```
> chore: :arrow_up:  vue 2.6.14 => 2.7.0 vuetify 2.6.6 => 2.6.7

- src/views/observe/alert/history/components/HistorySearch.vue
Fixes #
Reference to #
```release-note
NONE
```
> style: :lipstick: add alert history query label

- src/layouts/sidebar/sidebar_items.js
- src/mixins/select.js
- src/utils/icon.js
- src/views/resource/ingress/components/IngressBaseForm/IngressRuleForm.vue
- src/views/resource/ingress/components/IngressBaseForm/IngressRuleItem.vue
- src/views/resource/ingress/components/IngressBaseForm/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix ingress pathType field error bug

- src/views/observe/overview/components/OverviewList/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> style: :art: update observe dashboard icon

- src/views/resource/ingress/components/IngressBaseForm/IngressRuleForm.vue
- src/views/resource/ingress/components/IngressBaseForm/IngressRuleItem.vue
- src/views/resource/ingress/components/IngressBaseForm/index.vue
- src/views/resource/ingress/components/ResourceInfo.vue
Fixes #
Reference to #
```release-note
NONE
```
> perf: :ambulance: support ingress port name and port number

- src/components/BaseCollapseChips.vue
- src/components/BaseTipChips.vue
- src/views/appstore/index.vue
- src/views/observe/overview/components/OverviewList/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix appstore tag filter no data bug

- src/views/observe/components/ProjectEnvironmentTree.vue
- src/views/observe/log/config/flow/components/AddFlow.vue
- src/views/observe/log/config/flow/components/UpdateFlow.vue
- src/views/observe/log/config/output/components/OutputBaseForm/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix logging operator config namespace not correct bug

- src/assets/styles/markdown.scss
- src/layouts/header/Header.vue
- src/plugins/tip.js
- src/router/model_store.js
- src/router/platform.js
- src/views/modelstore/components/Breadcrumb.vue
- src/views/modelstore/components/Deploy.vue
- src/views/modelstore/components/ModelCard/index.vue
- src/views/modelstore/components/ModelFilter/index.vue
- src/views/modelstore/components/RegistrySelect.vue
- src/views/modelstore/components/VersionSelect.vue
- src/views/modelstore/components/detail_tabs/Runtime/index.vue
- src/views/setting/model_registry/components/AddModelRegistry.vue
- src/views/setting/model_registry/components/UpdateModelRegistry.vue
- src/views/setting/model_registry/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> style: :art: modify model store name

- Dockerfile
Fixes #
Reference to #
```release-note
NONE
```
> chore: :wrench: update dockerfile

- src/router/admin_workspace.js
- src/router/workspace.js
- src/views/resource/node/components/GpuScheduleForm.vue
Fixes #
Reference to #
```release-note
NONE
```
> :bug: fix node gpu schedule data not correct bug

- src/views/appstore/components/DeployWizard/Param/MinMaxParam.vue
- src/views/resource/environment/components/base/ResourceQuota.vue
- src/views/tenant/tenant/components/ResourceList/ResourceBaseForm/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix gpu tenant resource quota setting

- src/layouts/header/components/TenantSelect.vue
- src/views/observe/log/viewer/components/LogQueryHistory.vue
- src/views/resource/appmanifest/components/AppResourceFileList/AddResourceFile.vue
- src/views/resource/components/common/NamespaceFilter.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix router push async data not correct bug

- src/views/resource/environment/components/ResourceQuota.vue
- src/views/resource/environment/components/base/ResourceQuota.vue
- src/views/resource/node/components/ResourceInfo.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix environment gpu resource scale bug

- nginx.conf.template
- src/views/modelstore/components/DeployWizard/DeployBaseConf.vue
- vue.config.js
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix env select bug

- src/views/modelstore/components/DeployWizard/DeployAdvancedConf/ResourceConf.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix model gpu schedule

- src/mixins/resource.js
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix nvidia gpu resource quota field error bug

- src/mixins/resource.js
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix create environment with gpu data error bug

- src/views/modelstore/components/Breadcrumb.vue
- src/views/setting/model_registry/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix model sync status SUCCEED => SUCCESS

- src/views/microservice/service/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix microservice service filter error bug

- src/router/platform.js
- vue.config.js
Fixes #
Reference to #
```release-note
NONE
```
> style: :art: add template sidebar

- package.json
- src/views/resource/components/common/ContainerLog.vue
- src/views/resource/components/common/PodList.vue
- src/views/resource/log/index.vue
- src/views/resource/pod/components/ContainerItems.vue
- src/views/resource/pod/components/ContainerList.vue
Fixes #
Reference to #
```release-note
NONE
```
> perf: :ambulance: add init container to container log

- src/views/resource/components/common/PodList.vue
- src/views/resource/log/index.vue
- src/views/resource/pod/components/ContainerItems.vue
- src/views/resource/pod/components/ContainerList.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix container log initcontainer not exist occured error bug

- package.json
- src/views/resource/components/common/Terminal.vue
- vue.config.js
- yarn.lock
Fixes #
Reference to #
```release-note
NONE
```
> perf: :arrow_up: xterm 3.x => 4.x

- src/views/resource/environment/components/EnvironmentBaseForm/index.vue
- src/views/resource/project/components/ProjectBaseForm.vue
- src/views/resource/workload/components/WorkloadBaseForm/ContainerImage/container_section/ContainerRunCommand.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix environment and project name regex vetify error bug

- src/views/resource/workload/components/WorkloadBaseForm/ContainerImage/ContainerImageSelect.vue
- src/views/resource/workload/components/WorkloadBaseForm/ContainerImage/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix workload image form data error bug

- src/i18n/messages/en.json
- src/i18n/messages/zh-Hans.json
- src/layouts/header/Translate.vue
- src/router/index.js
- src/views/appstore/list.vue
- src/views/modelstore/components/DeployWizard/DeployAdvancedConf/Args.vue
- src/views/modelstore/components/DeployWizard/DeployAdvancedConf/Command.vue
- src/views/modelstore/components/DeployWizard/DeployAdvancedConf/index.vue
- src/views/modelstore/components/detail_tabs/Files.vue
- src/views/modelstore/detail.vue
- src/views/resource/dashboard/components/AuditList.vue
- src/views/resource/dashboard/components/DashboardCard.vue
- src/views/resource/dashboard/components/EventList.vue
- src/views/resource/dashboard/i18n/locales.json
- src/views/setting/model_registry/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix title i18n show bug, optimization model deploy component

- src/views/microservice/app/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix mesh loading always when plugin istio not enabled bug

- src/views/authentication/index.vue
- src/views/observe/monitor/dashboard/components/ContainerSelect.vue
- src/views/observe/monitor/dashboard/components/GraphBaseForm.vue
- src/views/observe/monitor/dashboard/index.vue
- src/views/observe/monitor/metrics/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> perf: :ambulance: remove name from monitor dashboard form

- src/views/observe/monitor/config/index.vue
- src/views/observe/monitor/i18n/zh-Hans.json
- src/views/observe/monitor/metrics/components/MetricsItem.vue
- src/views/observe/monitor/metrics/components/MetricsSuggestion.vue
- src/views/observe/monitor/metrics/components/ResourceSelectCascade.vue
- src/views/observe/monitor/metrics/index.vue
- src/views/observe/monitor/mixins/metrics.js
- src/views/setting/monitor/components/ResourceInfo.vue
- src/views/setting/monitor/i18n/zh-Hans.json
- src/views/tool/user/components/AccessToken/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> docs: :memo: add i18n

- src/components/BaseApexAreaChart.vue
- src/components/BaseLogo.vue
- src/i18n/messages/en.json
- src/i18n/messages/zh-Hans.json
- src/layouts/header/components/About.vue
- src/views/observe/integrated/index.vue
- src/views/observe/monitor/dashboard/components/GraphMax.vue
- src/views/observe/monitor/dashboard/index.vue
- src/views/observe/monitor/metrics/components/ResourceSelectCascade.vue
- src/views/observe/overview/components/OverviewList/Duration.vue
- src/views/resource/cluster/components/OverScaleResource.vue
- src/views/resource/cluster/index.vue
- src/views/resource/components/common/BasicResourceInfo.vue
- src/views/resource/pod/components/ContainerItems.vue
- src/views/resource/pod/index.vue
- src/views/resource/service/index.vue
- src/views/resource/workload/components/ResourceAdvise.vue
- src/views/resource/workload/index.vue
- src/views/setting/model_registry/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> perf: :zap: optimization pod gpu show, add about card link

- src/api/resource/app.js
- src/views/modelstore/components/detail_tabs/Runtime/components/tasks/ConversationText.vue
- src/views/modelstore/components/detail_tabs/Runtime/components/tasks/ImageSegmentation.vue
- src/views/modelstore/components/detail_tabs/Runtime/components/tasks/QuestionAnswer.vue
- src/views/modelstore/components/detail_tabs/Runtime/components/tasks/SingleFile.vue
- src/views/modelstore/components/detail_tabs/Runtime/components/tasks/SingleImage.vue
- src/views/modelstore/components/detail_tabs/Runtime/components/tasks/SingleText.vue
- src/views/modelstore/components/detail_tabs/Runtime/components/tasks/SingleTextInputs.vue
- src/views/modelstore/components/detail_tabs/Runtime/components/tasks/TableQuestionAnswer.vue
- src/views/modelstore/components/detail_tabs/Runtime/components/tasks/VisualQuestionAnswer.vue
- src/views/modelstore/components/detail_tabs/Runtime/components/tasks/ZeroShotClassification.vue
- src/views/observe/alert/history/components/HistorySearch.vue
- src/views/observe/integrated/components/IntergatedCenter/MiddlewareMetrics/index.vue
- src/views/observe/integrated/i18n/en.json
- src/views/observe/integrated/i18n/ja.json
- src/views/observe/integrated/i18n/zh-Hans.json
Fixes #
Reference to #
```release-note
NONE
```
> perf: :zap: optimization middleware integated status

- src/api/visualization/monitor.js
- src/components/BaseApexAreaChart.vue
- src/i18n/en.json
- src/i18n/ja.json
- src/i18n/zh-Hans.json
- src/i18n/zh-Hant.json
- src/router/admin_observe.js
- src/router/observe.js
- src/views/authentication/index.vue
- src/views/observe/monitor/app/components/ServiceSelect.vue
- src/views/observe/monitor/app/index.vue
- src/views/observe/monitor/dashboard/index.vue
- src/views/observe/trace/index.vue
- src/views/resource/cluster/components/MetricMonitor.vue
Fixes #
Reference to #
```release-note
NONE
```
> perf: :zap: optimization login page, optimization app performance trace

- README.md
- src/router/admin_observe.js
- src/views/observe/components/ProjectEnvSelectCascade.vue
- src/views/observe/log/i18n/en.json
- src/views/observe/log/i18n/ja.json
- src/views/observe/log/i18n/zh-Hans.json
- src/views/observe/log/i18n/zh-Hant.json
- src/views/observe/log/viewer/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix app monitor router bug

- src/components/BaseApexAreaChart.vue
- src/store/index.js
- src/views/observe/monitor/app/index.vue
- src/views/observe/trace/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> perf: :zap: optimization app preformance trace page

- package.json
- src/App.vue
- src/components/BaseBarChart.vue
- src/components/BasePieChart.vue
- src/components/BaseRadialBarChart.vue
- src/mixins/select.js
- src/views/modelstore/components/detail_tabs/Runtime/index.vue
- src/views/observe/log/viewer/components/LogBar.vue
- src/views/observe/log/viewer/components/LogQuery/LabelSelector/index.vue
- src/views/observe/log/viewer/components/LogQuery/index.vue
- src/views/observe/log/viewer/components/LogTable/index.vue
- src/views/observe/log/viewer/index.vue
- src/views/observe/monitor/app/index.vue
- src/views/resource/environment/components/ResourceQuota.vue
- src/views/resource/environment/components/base/LimitRange.vue
- src/views/resource/environment/components/base/ResourceChart.vue
- src/views/resource/node/components/ResourceInfo.vue
- src/views/tenant/tenant/components/ResourceList/ResourceBaseForm/ResourceChart.vue
- yarn.lock
Fixes #
Reference to #
```release-note
NONE
```
> :zap: add radial bar chart

- src/components/BaseAreaChart.vue
- src/views/observe/monitor/app/index.vue
- src/views/observe/monitor/dashboard/components/GraphMax.vue
- src/views/observe/monitor/dashboard/components/VariableSelect.vue
- src/views/observe/monitor/dashboard/index.vue
- src/views/resource/plugin/components/CheckPluginVersion.vue
- src/views/resource/plugin/i18n/en.json
- src/views/resource/plugin/i18n/ja.json
- src/views/resource/plugin/i18n/zh-Hans.json
- src/views/resource/plugin/i18n/zh-Hant.json
- src/views/resource/plugin/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> perf: :zap: optimization chart.js show

- src/views/observe/integrated/components/IntergatedCenter/MiddlewareMetrics/index.vue
- src/views/observe/log/i18n/zh-Hans.json
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix middleware monitor nameOverride error bug

- src/views/microservice/service/components/virtual_service/AddVirtualService.vue
- src/views/microservice/service/components/virtual_service/UpdateVirtualService.vue
- src/views/observe/overview/components/OverviewList/LogRateChart.vue
- src/views/observe/overview/components/OverviewList/index.vue
- src/views/resource/gateway/components/AddGateway.vue
- src/views/resource/gateway/components/UpdateGateway.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix i18n bugs

- src/views/observe/log/viewer/components/LogTable/LogPodMonitor.vue
- src/views/observe/log/viewer/index.vue
- src/views/resource/appmanifest/components/AppResourceFileList/index.vue
- src/views/resource/pod/components/PodMonitor.vue
- src/views/resource/workload/components/WorkloadMonitor.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix appmanifest i18n bug

- src/components/BaseAreaChart.vue
- src/layouts/Container.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix chart.js render time step bug

- src/api/resource/plugin.js
- src/views/observe/monitor/dashboard/components/DashboardBaseForm.vue
- src/views/resource/plugin/components/CheckPluginVersion.vue
- src/views/resource/plugin/components/InstallPluginSchema/PluginInfo.vue
- src/views/resource/plugin/components/InstallPluginSchema/SchemaRender/SchemaForm.vue
- src/views/resource/plugin/components/InstallPluginSchema/SchemaRender/ValuesForm.vue
- src/views/resource/plugin/components/InstallPluginSchema/SchemaRender/index.vue
- src/views/resource/plugin/components/InstallPluginSchema/index.vue
- src/views/resource/plugin/components/UpgradeTip.vue
- src/views/resource/plugin/components/VersionSelect.vue
- src/views/resource/plugin/i18n/en.json
- src/views/resource/plugin/i18n/ja.json
- src/views/resource/plugin/i18n/zh-Hans.json
- src/views/resource/plugin/i18n/zh-Hant.json
- src/views/resource/plugin/index.vue
- vue.config.js
Fixes #
Reference to #
```release-note
NONE
```
> feat: :sparkles: support plugin custom installed params

- src/api/resource/plugin.js
- src/components/BaseSubTitle.vue
- src/views/appstore/components/Subsection.vue
- src/views/resource/plugin/components/InstallPluginSchema/SchemaRender/SchemaForm.vue
- src/views/resource/plugin/components/InstallPluginSchema/SchemaRender/index.vue
- src/views/resource/plugin/components/InstallPluginSchema/index.vue
- src/views/resource/plugin/i18n/en.json
- src/views/resource/plugin/i18n/ja.json
- src/views/resource/plugin/i18n/zh-Hans.json
- src/views/resource/plugin/i18n/zh-Hant.json
- src/views/resource/plugin/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix plugin custom params few bugs

- src/layouts/header/Message.vue
- src/views/resource/cluster/components/ResourceChart.vue
- src/views/tenant/tenant/components/ResourceList/ResourceBaseForm/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix apply resource limit error bug

- src/api/index.js
- src/components/BaseAreaChart.vue
- src/i18n/en.json
- src/i18n/ja.json
- src/i18n/zh-Hans.json
- src/i18n/zh-Hant.json
- src/views/observe/overview/components/OverviewList/LogRateChart.vue
- src/views/observe/overview/i18n/en.json
- src/views/observe/overview/i18n/ja.json
- src/views/observe/overview/i18n/zh-Hans.json
- src/views/observe/overview/i18n/zh-Hant.json
- src/views/resource/environment/components/ResourceQuota.vue
- src/views/resource/environment/components/base/ResourceChart.vue
- src/views/resource/ingress/components/IngressBaseForm/IngressRuleForm.vue
- src/views/resource/node/components/ResourceInfo.vue
- src/views/tenant/tenant/components/ResourceList/ResourceBaseForm/ResourceChart.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix ingress, chart.js, version tip few bugs

- src/components/BaseAreaChart.vue
- src/views/observe/monitor/metrics/components/MetricsItem.vue
- src/views/observe/overview/components/OverviewList/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> style: :zap: optimization chart.js style

- src/views/observe/monitor/metrics/components/ResourceSelectCascade.vue
- src/views/setting/prometheus/components/AddTemplate.vue
- src/views/setting/prometheus/components/UpdateTemplate.vue
- src/views/setting/prometheus/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix prometheus template create and delete params error bug

- src/views/resource/plugin/components/CheckPluginVersion.vue
- src/views/resource/plugin/components/InstallPluginSchema/SchemaRender/SchemaForm.vue
- src/views/resource/plugin/components/UpgradeMessage.vue
- src/views/resource/plugin/i18n/en.json
- src/views/resource/plugin/i18n/ja.json
- src/views/resource/plugin/i18n/zh-Hans.json
- src/views/resource/plugin/i18n/zh-Hant.json
- src/views/resource/plugin/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix plugin custom params installed error bug

- src/views/observe/alert/history/components/HistorySearch.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix alert history search filters

- src/mixins/table.js
- src/views/observe/alert/history/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix table createAt sort no effect bug

- src/App.vue
- src/views/observe/integrated/components/IntergatedCenter/Logging.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix log collect create bug, optimization login auth error bug

- src/views/observe/components/ProjectEnvironmentLayout.vue
- src/views/observe/integrated/components/IntergatedCenter/MiddlewareMetrics/index.vue
- src/views/observe/integrated/components/IntergatedCenter/index.vue
- src/views/observe/log/config/alert_rule/index.vue
- src/views/observe/monitor/config/prometheusrule/index.vue
- src/views/observe/overview/components/OverviewList/Duration.vue
- src/views/observe/overview/components/OverviewList/ErrorLogRateChart.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix project environment tree trigger refresh bug

- src/mixins/select.js
- src/views/appstore/components/DeployWizard/AppStoreDeployLoading.vue
- src/views/observe/components/ProjectEnvSelectCascade.vue
Fixes #
Reference to #
```release-note
NONE
```
> perf: :zap: add env type chip label

- src/components/BaseRadialBarChart.vue
- src/views/microservice/components/PluginPass.vue
- src/views/microservice/istio/authorization_policy/index.vue
- src/views/microservice/istio/gateway/index.vue
- src/views/microservice/istio/peer_authentication/index.vue
- src/views/microservice/istio/service_entry/index.vue
- src/views/microservice/istio/sidecar/index.vue
- src/views/microservice/istio_gateway/detail.vue
- src/views/microservice/istio_gateway/index.vue
- src/views/microservice/service/detail.vue
- src/views/microservice/service/index.vue
- src/views/microservice/workload/detail.vue
- src/views/microservice/workload/index.vue
- src/views/observe/monitor/dashboard/components/DashboardBaseForm.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix mesh env select no effect bug

- src/utils/prometheus.js
- src/views/resource/pod/components/ContainerList.vue
- src/views/resource/pod/components/PodMonitor.vue
- src/views/resource/workload/components/WorkloadMonitor.vue
Fixes #
Reference to #
```release-note
NONE
```
> perf: :zap: optimization prometheus ql to fit chart.js render

- src/views/observe/integrated/components/IntergatedCenter/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix middleware integated next btn not exist bug

- src/components/BaseAreaChart.vue
- src/views/observe/monitor/config/prometheusrule/components/PrometheusRuleBaseForm/Rule/index.vue
- src/views/observe/monitor/config/receiver/index.vue
- src/views/observe/monitor/metrics/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix chart.js x time overlap bug

- src/views/observe/monitor/config/prometheusrule/index.vue
- src/views/resource/components/common/Terminal.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix terminal size bug

- src/views/microservice/app/index.vue
- src/views/modelstore/components/ModelCard/index.vue
- src/views/observe/trace/index.vue
- src/views/resource/cluster/index.vue
- src/views/resource/gateway/i18n/en.json
- src/views/resource/plugin/index.vue
- src/views/setting/model_registry/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> style: :lipstick: fit i18n en flag styles

- src/components/BaseClusterHeader.vue
- src/components/BaseMicroServiceHeader.vue
- src/components/BaseTenantHeader.vue
- src/views/resource/app/index.vue
- src/views/resource/appmanifest/components/DeployApp.vue
- src/views/resource/components/common/EventTip.vue
- src/views/resource/pod/components/RestartTip.vue
- src/views/resource/pod/i18n/en.json
- src/views/resource/pod/i18n/ja.json
- src/views/resource/pod/i18n/zh-Hans.json
- src/views/resource/pod/i18n/zh-Hant.json
- src/views/resource/pod/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> feat: :sparkles: add pod list container state tip

- CHANGELOG
- package.json
- src/views/observe/log/config/output/components/OutputBaseForm/Elasticsearch.vue
- src/views/observe/log/config/output/components/OutputBaseForm/Kafka.vue
- src/views/observe/log/config/output/components/OutputBaseForm/Loki.vue
- src/views/observe/log/config/output/components/OutputBaseForm/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix log output edit data is null bug

- src/views/modelstore/components/ModelCard/index.vue
- src/views/resource/components/common/GpuTip.vue
Fixes #
Reference to #
```release-note
NONE
```
> style: :lipstick: update model card style

- src/i18n/en.json
- src/i18n/ja.json
- src/i18n/zh-Hans.json
- src/i18n/zh-Hant.json
- src/layouts/header/components/ApproveResource.vue
- src/views/resource/components/common/Terminal/FileDownloader.vue
- src/views/resource/components/common/Terminal/FileUploader.vue
- src/views/resource/components/common/Terminal/index.vue
- src/views/resource/components/i18n/en.json
- src/views/resource/components/i18n/ja.json
- src/views/resource/components/i18n/zh-Hans.json
- src/views/resource/components/i18n/zh-Hant.json
- src/views/resource/dashboard/components/ResourceList/ScaleResource.vue
- src/views/resource/dashboard/components/ResourceList/index.vue
- src/views/resource/environment/components/base/ResourceQuota.vue
- src/views/tenant/tenant/components/ResourceList/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix refresh terminal occoured file error bug

- src/views/observe/monitor/app/index.vue
- src/views/resource/pod/components/ContainerItems.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix app trace auto refresh bug

- src/layouts/header/components/ApproveResource.vue
- src/views/tenant/tenant/components/ResourceList/ResourceBaseForm/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix resource quota approval clear data bug

- nginx.conf.template
Fixes #
Reference to #
```release-note
NONE
```
> chore: :memo: set client_max_body_size to nginx

- src/views/modelstore/components/DeployWizard/DeployAdvancedConf/ResourceConf.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix model deploy gpu resource limit allocate bug

- src/i18n/en.json
- src/i18n/ja.json
- src/i18n/zh-Hans.json
- src/i18n/zh-Hant.json
- src/views/observe/monitor/config/prometheusrule/components/AddPrometheusRule.vue
- src/views/observe/monitor/config/prometheusrule/components/PrometheusRuleBaseForm/Rule/index.vue
- src/views/observe/monitor/config/prometheusrule/components/UpdatePrometheusRule.vue
- src/views/resource/components/common/GpuTip.vue
- src/views/resource/components/common/Terminal/FileDownloader.vue
- src/views/resource/components/common/Terminal/FileUploader.vue
- src/views/resource/components/common/Terminal/index.vue
- src/views/resource/dashboard/components/ResourceList/index.vue
- src/views/tenant/tenant/components/ResourceList/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> :bug: fix terminal exec bug

- src/mixins/resource.js
- src/store/index.js
- src/utils/helpers.js
- src/views/modelstore/detail.vue
- src/views/resource/components/common/Terminal/index.vue
- src/views/resource/components/i18n/en.json
- src/views/resource/components/i18n/ja.json
- src/views/resource/components/i18n/zh-Hans.json
- src/views/resource/components/i18n/zh-Hant.json
- src/views/resource/dashboard/components/ResourceList/index.vue
- src/views/resource/environment/components/ResourceQuota.vue
- src/views/tenant/tenant/index.vue
- vue.config.js
Fixes #
Reference to #
```release-note
NONE
```
> perf: :zap: optimization container file downloader and uploader

- .versionrc.js
- CHANGELOG.md
- package.json
- src/api/visualization/monitor.js
- src/components/BaseAreaChart.vue
- src/components/BaseBarChart.vue
- src/components/BasePieChart.vue
- src/components/BaseRadialBarChart.vue
- src/views/observe/monitor/dashboard/index.vue
- src/views/resource/components/common/DetailContainer.vue
- src/views/resource/components/common/Terminal/index.vue
- src/views/resource/cronjob/components/ResourceInfo.vue
- src/views/resource/job/components/ResourceInfo.vue
- src/views/resource/pod/components/ResourceInfo.vue
- src/views/resource/workload/components/ResourceInfo.vue
- yarn.lock
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix monitor dashboard api method post => put

- README.md
- src/views/resource/components/common/Terminal/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix file download regex match

- package.json
- src/views/observe/monitor/dashboard/index.vue
- yarn.lock
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix monitor dashboard switch env variable not clear bug

- src/views/resource/app/detail.vue
- src/views/resource/app/index.vue
- src/views/resource/cluster/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix application message bus data not filter type bug

- babel.config.js
- commitlint.config.js
- package.json
- src/views/resource/node/detail.vue
- vite.config.js
- yarn.lock
Fixes #
Reference to #
```release-note
NONE
```
> build: :wrench: optimization vite conf

- package.json
- pnpm-lock.yaml
- src/extension/index.js
- src/views/resource/components/common/Terminal/index.vue
- vite.config.js
Fixes #
Reference to #
```release-note
NONE
```
> refactor: :bug: fix js-yaml dump bug

- src/views/resource/pod/components/ContainerList.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix container list status is null bug

- src/components/BaseDatetimePicker.vue
- src/views/setting/broadcast/components/BroadcastBaseForm.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix broadcast datetimepicker default value bug

- src/components/BaseAreaChart.vue
- src/views/observe/monitor/dashboard/components/GraphMax.vue
- src/views/observe/monitor/dashboard/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> perf: :zap: close chart.js animation

- src/components/BaseClusterHeader.vue
- src/components/BaseEnvironmentHeader.vue
- src/router/admin_observe.ts
- src/router/admin_workspace.ts
- src/router/app_store.ts
- src/router/dashboard.ts
- src/router/entry_microservice.ts
- src/router/global.ts
- src/router/microservice.ts
- src/router/model_store.ts
- src/router/observe.ts
- src/router/platform.ts
- src/router/project_workspace.ts
- src/router/tool.ts
- src/router/user_center.ts
- src/router/workspace.ts
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix base environment header get data error bug

- package.json
- pnpm-lock.yaml
- src/App.vue
- src/components/BaseAreaChart.vue
- src/components/BaseBreadcrumb.vue
- src/components/BaseInfoCard.vue
- src/components/BaseItemGroup.vue
- src/components/BaseItemSubGroup.vue
- src/components/BaseListItemForDetail.vue
- src/components/BaseLogo.vue
- src/components/BasePluginPass.vue
- src/components/BaseProgress.vue
- src/components/BaseSnackBar.vue
- src/components/BaseStatus.vue
- src/components/BaseViewportHeader.vue
- src/composition/proxy.ts
- src/main.ts
- src/router/index.ts
- src/views/resource/cluster/components/EdgeCluster.vue
- src/views/resource/cluster/components/EdgeStatusTip.vue
- src/views/resource/dashboard/components/ResourceList/EdgeCluster.vue
- src/views/resource/edge/index.vue
- vite.config.js
Fixes #
Reference to #
```release-note
NONE
```
> refactor: 🔨 reflact base component to composition api style

- src/components/BaseItemGroup.vue
- src/types/base.ts
- src/types/configmap.ts
- src/types/cronjob.ts
- src/types/daemonset.ts
- src/types/deployment.ts
- src/types/edge_cluster.ts
- src/types/edge_hub.ts
- src/types/ingress.ts
- src/types/job.ts
- src/types/kubernetes.ts
- src/types/namespace.ts
- src/types/node.ts
- src/types/persistentvolumeclaim.ts
- src/types/pod.ts
- src/types/secret.ts
- src/types/service.ts
- src/types/statefulset.ts
- src/types/storageclass.ts
- src/views/resource/cluster/components/EdgeCluster.vue
- src/views/resource/cluster/components/EdgeClusterForm/RegisterMessage.vue
- src/views/resource/cluster/components/EdgeClusterForm/index.vue
- src/views/resource/cluster/components/EdgeStatusTip.vue
- src/views/resource/dashboard/components/ResourceList/EdgeCluster.vue
- src/views/resource/edge/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> perf: :zap: add k8s models, fix edge bugs

- src/components/BaseClusterHeader.vue
- src/components/BaseEnvironmentHeader.vue
- src/composition/cluster.ts
- src/i18n/en.json
- src/i18n/ja.json
- src/i18n/zh-Hans.json
- src/i18n/zh-Hant.json
- src/mixins/resource.ts
- src/types/cluster.ts
- src/views/resource/cluster/components/AllocateEdgeCluster/TenantProjEnvSelectCascade.vue
- src/views/resource/cluster/components/AllocateEdgeCluster/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix filter namespace not effetc bug

- src/components/BaseClusterHeader.vue
- src/components/BaseEnvironmentHeader.vue
- src/composition/telemetry.ts
- src/types/opentelemetry.ts
- src/views/observe/monitor/app/components/Overview.vue
- src/views/observe/monitor/app/components/ServiceList.vue
- src/views/observe/monitor/app/components/Trace.vue
- src/views/observe/monitor/app/index1.vue
- src/views/observe/monitor/i18n/en.json
- src/views/observe/monitor/i18n/ja.json
- src/views/observe/monitor/i18n/zh-Hans.json
- src/views/observe/monitor/i18n/zh-Hant.json
- src/views/resource/cluster/components/AllocateEdgeCluster/TenantProjEnvSelectCascade.vue
- src/views/resource/cluster/components/AllocateEdgeCluster/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix label edge cluster bug

- src/composition/proxy.ts
- src/views/resource/cluster/components/EdgeClusterForm/RegisterMessage.vue
- vite.config.js
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix edge cluster copy command not effect bug

- package.json
- pnpm-lock.yaml
- src/components/BaseTimelineChart.vue
- src/views/observe/monitor/app/components/Trace/Trace.vue
Fixes #
Reference to #
```release-note
NONE
```
> perf: :zap: add log and trace link from app monitor page

- src/types/axios.ts
- src/views/observe/alert/history/components/HistorySearch.vue
- src/views/observe/alert/history/index.vue
- src/views/observe/alert/i18n/en.json
- src/views/observe/alert/i18n/ja.json
- src/views/observe/alert/i18n/zh-Hans.json
- src/views/observe/alert/i18n/zh-Hant.json
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix url encode bug

- src/components/BaseTimelineChart.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix timeline chart step too small bug

- src/views/resource/cluster/components/EdgeClusterDetail.vue
- src/views/resource/cluster/components/ResourceChart.vue
- src/views/resource/edge/components/EdgeCluster.vue
- src/views/resource/edge/detail.vue
Fixes #
Reference to #
```release-note
NONE
```
> perf: :zap: add kubectl and update to tenant edge cluster detail page

- src/views/resource/appmanifest/components/AppBaseForm.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix app name check regex not correct bug

- src/views/observe/log/viewer/components/LogTable/LogMonitor/LogLabel.vue
- src/views/resource/appmanifest/components/AppBaseForm.vue
- src/views/resource/appmanifest/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> perf: :zap: optimization log monitor labels style

- src/i18n/zh-Hans.json
- src/router/global.ts
- src/views/tool/schema/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> perf: :zap: add json schema validate tools

- .github/workflows/build.yml
- src/components/BaseBarChart.vue
- src/views/authentication/index.vue
- src/views/observe/log/viewer/index.vue
- src/views/observe/trace/index.vue
- src/views/resource/cluster/components/EdgeClusterForm/SelectCloudCluster.vue
Fixes #
Reference to #
```release-note
NONE
```
> build: :chrone: update build.yml

- CHANGELOG.md
- src/extension/sentry.ts
Fixes #
Reference to #
```release-note
NONE
```
> chore: :chrone: optimization sentry config to .env file

- src/types/opentelemetry.ts
- src/views/observe/log/i18n/en.json
- src/views/observe/log/i18n/ja.json
- src/views/observe/log/i18n/zh-Hans.json
- src/views/observe/log/i18n/zh-Hant.json
- src/views/observe/log/viewer/components/LogTable/LogMonitor/Trace.vue
- src/views/observe/log/viewer/components/LogTable/LogMonitor/index.vue
- src/views/resource/gateway/components/AddGateway.vue
Fixes #
Reference to #
```release-note
NONE
```
> perf: :zap: support log trace chart and link to jaeger page

- src/views/resource/plugin/components/InstallPluginSchema/SchemaRender/SchemaForm.vue
Fixes #
Reference to #
```release-note
NONE
```
> perf: :zap: support i18n to cluster plugin schema

- src/components/BaseAreaChart.vue
- src/constants/prometheus.ts
- src/views/appstore/components/DeployWizard/index.vue
- src/views/observe/log/i18n/en.json
- src/views/observe/log/i18n/ja.json
- src/views/observe/log/i18n/zh-Hans.json
- src/views/observe/log/i18n/zh-Hant.json
- src/views/observe/log/viewer/components/LogTable/LogMonitor/NodeMonitor.vue
- src/views/resource/node/components/NodeMonitor.vue
- src/views/resource/node/i18n/en.json
- src/views/resource/node/i18n/ja.json
- src/views/resource/node/i18n/zh-Hans.json
- src/views/resource/node/i18n/zh-Hant.json
- src/views/resource/plugin/components/InstallPluginSchema/SchemaRender/SchemaForm.vue
Fixes #
Reference to #
```release-note
NONE
```
> perf: :zap:  Add Host metics pannel "Memory Used" group by type

- CHANGELOG.md
- src/i18n/en.json
- src/i18n/ja.json
- src/i18n/zh-Hans.json
- src/i18n/zh-Hant.json
- src/views/appstore/components/DeployWizard/Param/TextFieldParam.vue
- src/views/appstore/components/DeployWizard/Param/index.vue
- src/views/appstore/components/DeployWizard/index.vue
- src/views/modelstore/components/DeployWizard/DeployBaseConf.vue
- src/views/resource/dashboard/components/ResourceList/index.vue
- src/views/resource/plugin/components/InstallPluginSchema/PluginInfo.vue
- src/views/resource/plugin/components/InstallPluginSchema/SchemaRender/SchemaForm.vue
Fixes #
Reference to #
```release-note
NONE
```
> perf: :zap: enhancement json schema render

- CHANGELOG.md
- package.json
- src/views/observe/trace/index.vue
- src/views/setting/monitor/components/ResourceInfo.vue
- src/views/setting/oauth/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix monitor template detail page list graphs error bug

- CHANGELOG.md
- src/views/resource/components/i18n/en.json
- src/views/resource/components/i18n/ja.json
- src/views/resource/components/i18n/zh-Hans.json
- src/views/resource/components/i18n/zh-Hant.json
- src/views/resource/workload/components/WorkloadBaseForm/ContainerImage/container_section/ContainerRunCommand.vue
- src/views/resource/workload/i18n/en.json
- src/views/resource/workload/i18n/ja.json
- src/views/resource/workload/i18n/zh-Hans.json
- src/views/resource/workload/i18n/zh-Hant.json
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: remove required validate for container command and args

- CHANGELOG.md
- nginx.conf.template
- src/views/modelstore/components/detail_tabs/Runtime/components/tasks/ConversationText.vue
- src/views/modelstore/components/detail_tabs/Runtime/components/tasks/FileInputs.vue
- src/views/modelstore/components/detail_tabs/Runtime/components/tasks/ImageSegmentation.vue
- src/views/modelstore/components/detail_tabs/Runtime/components/tasks/QuestionAnswer.vue
- src/views/modelstore/components/detail_tabs/Runtime/components/tasks/SingleImage.vue
- src/views/modelstore/components/detail_tabs/Runtime/components/tasks/TableQuestionAnswer.vue
- src/views/modelstore/components/detail_tabs/Runtime/components/tasks/TextInputs.vue
- src/views/modelstore/components/detail_tabs/Runtime/components/tasks/VisualQuestionAnswer.vue
- src/views/modelstore/components/detail_tabs/Runtime/components/tasks/ZeroShotClassification.vue
- src/views/modelstore/components/detail_tabs/Runtime/components/tasks/ZeroShotImageClassification.vue
- src/views/modelstore/components/detail_tabs/Runtime/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> style: :lipstick: optimization model experience styles

- CHANGELOG.md
- package.json
- src/views/modelstore/components/detail_tabs/Runtime/components/ModelExperience.vue
- src/views/modelstore/components/detail_tabs/Runtime/components/tasks/ImageSegmentation.vue
- src/views/modelstore/components/detail_tabs/Runtime/index.vue
- src/views/modelstore/components/detail_tabs/Runtime/mixins/params.ts
- src/views/modelstore/i18n/en.json
- src/views/modelstore/i18n/ja.json
- src/views/modelstore/i18n/zh-Hans.json
- src/views/modelstore/i18n/zh-Hant.json
- src/views/resource/app/i18n/en.json
- src/views/resource/app/i18n/ja.json
- src/views/resource/app/i18n/zh-Hans.json
- src/views/resource/app/i18n/zh-Hant.json
- src/views/resource/app/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> perf: :zap: optimization model experience

- src/composition/pod.ts
- src/types/modeldeployment.ts
- src/types/pod.ts
- src/views/modelstore/components/DeployWizard/DeployAdvancedConf/index.vue
- src/views/modelstore/components/DeployWizard/index.vue
- src/views/modelstore/components/detail_tabs/Runtime/components/ModelExperience.vue
- src/views/modelstore/components/detail_tabs/Runtime/index.vue
- src/views/modelstore/i18n/en.json
- src/views/modelstore/i18n/ja.json
- src/views/modelstore/i18n/zh-Hans.json
- src/views/modelstore/i18n/zh-Hant.json
- src/views/resource/app/i18n/en.json
- src/views/resource/app/i18n/ja.json
- src/views/resource/app/i18n/zh-Hans.json
- src/views/resource/app/i18n/zh-Hant.json
- src/views/resource/app/index.vue
- src/views/resource/components/common/PodList.vue
- src/views/resource/workload/components/PodItems.vue
- src/views/resource/workload/i18n/en.json
- src/views/resource/workload/i18n/ja.json
- src/views/resource/workload/i18n/zh-Hans.json
- src/views/resource/workload/i18n/zh-Hant.json
- src/views/resource/workload/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> perf: :zap: optimization model pages

- CHANGELOG.md
- src/views/modelstore/components/detail_tabs/Runtime/index.vue
- src/views/observe/monitor/app/components/Trace/Trace/index.vue
- src/views/resource/components/common/PodList.vue
- src/views/resource/workload/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> perf: :zap: optimization trace table width

- README.md
Fixes #
Reference to #
```release-note
NONE
```
> docs: :memo: fixed readme.md word spell error bug

- src/components/BaseTimelineChart.vue
- src/views/observe/log/config/alert_rule/index.vue
- src/views/observe/log/viewer/components/LogTable/LogMonitor/NodeMonitor.vue
- src/views/observe/log/viewer/components/LogTable/LogMonitor/Trace.vue
- src/views/observe/log/viewer/components/LogTable/LogMonitor/index.vue
- src/views/observe/monitor/app/components/Trace/Trace/index.vue
- src/views/observe/monitor/config/prometheusrule/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> perf: :zap: optimization trace chart style and alert rule channels

- package.json
- pnpm-lock.yaml
- src/composition/permission.ts
- src/mixins/permission.ts
- src/types/plugin.ts
- src/views/observe/overview/components/OverviewList/ErrorLogRateChart.vue
- src/views/observe/overview/components/OverviewList/K8sEvents/Chart/EventPieChart.vue
- src/views/observe/overview/components/OverviewList/K8sEvents/Chart/index.vue
- src/views/observe/overview/components/OverviewList/LogRateChart.vue
Fixes #
Reference to #
```release-note
NONE
```
> style: :lipstick: update few styles

- CHANGELOG.md
- src/api/log/viewer.ts
- src/types/prometheus_rule.ts
- src/views/observe/log/viewer/components/LogLine.vue
- src/views/observe/monitor/app/components/Trace/Trace/index.vue
- src/views/observe/monitor/config/prometheusrule/components/AddPrometheusRule.vue
- src/views/observe/monitor/config/prometheusrule/components/PrometheusRuleBaseForm/Rule/LabelMatchersForm.vue
- src/views/observe/monitor/config/prometheusrule/components/UpdatePrometheusRule.vue
Fixes #
Reference to #
```release-note
NONE
```
> perf: :zap: support label suggestion when create log alert rule

- CHANGELOG.md
- src/components/BaseDialog.vue
- src/components/BaseFullScreenDialog.vue
- src/components/BasePanel.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix progress bar missing bug

- CHANGELOG.md
- src/utils/icon.ts
- src/views/appstore/components/DeployWizard/index.vue
- src/views/resource/app/i18n/en.json
- src/views/resource/app/i18n/ja.json
- src/views/resource/app/i18n/zh-Hans.json
- src/views/resource/app/i18n/zh-Hant.json
- src/views/resource/app/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> refactor: :zap: add appstore repository name for list page

- CHANGELOG.md
- src/views/resource/app/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> perf: :zap: change repository field for appstore list page

- src/components/BaseClusterHeader.vue
- src/components/BaseEnvironmentHeader.vue
- src/composition/cluster.ts
- src/types/cluster.ts
- src/utils/icon.ts
- src/views/modelstore/components/ModelCard/index.vue
- src/views/resource/cluster/components/BasicMonitor/index.vue
- src/views/resource/project/components/EnvironmentList.vue
Fixes #
Reference to #
```release-note
NONE
```
> style: :lipstick: optimization model card styles

- CHANGELOG.md
- src/views/resource/appmanifest/components/AppBaseForm.vue
- src/views/resource/certmanager/components/AddCertificate.vue
- src/views/resource/certmanager/components/AddIssuer.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix app manifest create error bug

- CHANGELOG.md
- src/views/observe/monitor/config/prometheusrule/components/PrometheusRuleBaseForm/Receiver/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix generate alert message missing namespace bug

- src/components/BaseEnvironmentHeader.vue
- src/views/resource/environment/components/EnvironmentBaseForm/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix data not callback in form when edit environment bug

- CHANGELOG.md
- src/composition/cluster.ts
- src/composition/environment.ts
- src/composition/project.ts
- src/composition/tenant.ts
- src/extension/sentry.ts
- src/types/axios.ts
- src/views/resource/app/index.vue
- src/views/tool/audit/index1.vue1
Fixes #
Reference to #
```release-note
NONE
```
> style: :lipstick: optimization few styles

- CHANGELOG.md
- index.html
- nginx.conf.template
Fixes #
Reference to #
```release-note
NONE
```
> perf: :zap: remove index.html cache

- CHANGELOG.md
- src/assets/styles/common.scss
- src/components/BasePagination.vue
- src/composition/cluster.ts
- src/types/axios.ts
- src/views/resource/cluster/components/EdgeCluster.vue
- src/views/resource/dashboard/components/ResourceList/EdgeCluster.vue
- src/views/resource/edge/index.vue
- src/views/resource/workload/components/WorkloadBaseForm/ContainerImage/ContainerImageSelect.vue
- src/views/resource/workload/components/WorkloadBaseForm/ContainerImage/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix get docker registry secret from edge cluster error bug

- CHANGELOG.md
- src/components/BaseConfirm.vue
- src/i18n/en.json
- src/i18n/ja.json
- src/i18n/zh-Hans.json
- src/i18n/zh-Hant.json
- src/layouts/header/components/TenantSelect.vue
- src/store/index.ts
- src/views/appstore/components/Subsection.vue
- src/views/resource/components/common/Terminal/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix websocket state not correct bug and few syntax error bug

- CHANGELOG.md
- src/assets/styles/vuetify_overwrite.scss
- src/composition/user.ts
- src/views/appstore/components/DeployWizard/Param/index.vue
- src/views/tenant/tenant/components/ResourceList/ResourceBaseForm/ResourceChart.vue
- src/views/tenant/user/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix json schema render bug

- CHANGELOG.md
- src/composition/tenant.ts
- src/mixins/resource.ts
- src/views/observe/integrated/index.vue
- src/views/resource/appmanifest/components/AppResourceFileList/AddResourceFile.vue
- src/views/resource/appmanifest/components/AppResourceFileList/UpdateResourceFile.vue
- src/views/resource/workload/components/WorkloadBaseForm/index.vue
- src/views/tenant/tenant/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :zap: support custom kind for appmanifest

- CHANGELOG.md
- src/components/BaseConfirm.vue
- src/composition/cluster.ts
- src/composition/tenant.ts
- src/composition/user.ts
- src/types/cluster.ts
- src/types/tenant.ts
- src/utils/schema/cronjob.ts
- src/views/resource/appmanifest/components/AppResourceFileList/UpdateResourceFile.vue
- src/views/resource/cluster/components/EdgeClusterForm/RegisterMessage.vue
- src/views/resource/components/common/PodList.vue
- src/views/tenant/tenant/components/ResourceList/AddResource.vue
- src/views/tenant/tenant/components/ResourceList/ResourceBaseForm/index.vue
- src/views/tenant/tenant/components/ResourceList/ScaleResource.vue
- src/views/tenant/tenant/components/ResourceList/TenantMonitor.vue
- src/views/tenant/tenant/components/ResourceList/index.vue
- src/views/tenant/tenant/components/UserList/AddUser.vue
- src/views/tenant/tenant/components/UserList/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> refactor: :hammer: tenant center code upgrade to vue3

- CHANGELOG.md
- src/composition/user.ts
- src/views/resource/components/common/ContainerLog.vue
- src/views/resource/components/common/Terminal/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix can not change user role to admin bug

- CHANGELOG.md
- src/types/ai_model.ts
- src/views/resource/workload/components/WorkloadBaseForm/ContainerImage/ContainerImageSelect.vue
- src/views/setting/model_registry/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix workload can not list container type bug

- CHANGELOG.md
- index.html
- src/extension/index.ts
- src/layouts/header/components/About.vue
- src/types/helm.ts
- src/views/appstore/list.vue
- src/views/resource/app_configer/components/ConfigEditor.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix ace mode properties import bug

- CHANGELOG.md
- package.json
- pnpm-lock.yaml
- src/composition/environment.ts
- src/composition/workload.ts
- src/constants/resource.ts
- src/extension/sentry.ts
- src/types/axios.ts
- src/utils/schema.ts
- src/utils/table.ts
- src/views/resource/cluster/components/EdgeCluster.vue
- src/views/resource/dashboard/components/ResourceList/EdgeCluster.vue
- src/views/resource/edge/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> chore: :chrone: integrated browser cached data to sentry attachment

- CHANGELOG.md
- src/api/resource/apiresource.ts
- src/layouts/License.vue
- src/router/index.ts
- src/store/index.ts
- src/types/axios.ts
- src/views/resource/configmap/components/ConfigMapBaseForm/index.vue
- src/views/resource/cronjob/components/CronjobBaseForm/CronJobBaseInfo.vue
- src/views/resource/dashboard/index.vue
- src/views/resource/ingress/components/IngressBaseForm/index.vue
- src/views/resource/job/components/JobBaseForm/JobBaseInfo.vue
- src/views/resource/persistentvolumeclaim/components/PersistentVolumeClaimBaseForm.vue
- src/views/resource/secret/components/SecretBaseForm/index.vue
- src/views/resource/service/components/ServiceBaseForm/index.vue
- src/views/resource/workload/components/WorkloadBaseForm/WorkloadBaseInfo.vue
Fixes #
Reference to #
```release-note
NONE
```
> perf: :zap: optimization edge cluster switch api request cache

- CHANGELOG.md
- src/components/BaseParam/MultiSelectParam.vue
- src/types/base.ts
- src/utils/schema.ts
- src/views/appstore/index.vue
- src/views/modelstore/components/detail_tabs/Runtime/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix json schema init bug, fix app store list data bug

- CHANGELOG.md
- vite.config.ts
Fixes #
Reference to #
```release-note
NONE
```
> ci: :chrone: update vite config

- CHANGELOG.md
- vite.config.ts
Fixes #
Reference to #
```release-note
NONE
```
> ci: :chrone: update vie chunk cplit config

- CHANGELOG.md
- src/types/message.ts
- src/views/modelstore/components/DeployWizard/DeployAdvancedConf/ResourceConf.vue
- src/views/modelstore/detail.vue
- src/views/observe/monitor/config/prometheusrule/components/PrometheusRuleBaseForm/Rule/LabelMatchersForm.vue
- src/views/observe/monitor/config/prometheusrule/components/PrometheusRuleBaseForm/Rule/LabelMatchersItem.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix resource approve api bug

- pnpm-lock.yaml
- src/layouts/header/components/About.vue
- src/mixins/select.ts
- src/views/resource/workload/components/WorkloadBaseForm/ContainerImage/ContainerImageSelect.vue
- src/views/resource/workload/components/WorkloadBaseForm/ScheduleSelector/SelectorForm.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix create edge workload can not find registry secret bug

- src/views/observe/monitor/probe/components/ProbeMonitor.vue
- src/views/resource/components/common/Terminal/FileDownloader.vue
- src/views/resource/components/common/Terminal/FileUploader.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix edge pod upload url error bug

- src/views/resource/components/common/NamespaceFilter.vue
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix edge resource list namespace error bug

- .gitignore
- apps/kubegems/src/mixins/table.ts
- apps/kubegems/src/types/file.ts
- apps/kubegems/src/views/observe/alert/blacklist/index.vue
- apps/kubegems/src/views/observe/alert/history/index.vue
- apps/kubegems/src/views/observe/components/ProjectEnvironmentTree.vue
- apps/kubegems/src/views/observe/log/viewer/components/LogTable/LogMonitor/Trace.vue
- apps/kubegems/src/views/observe/log/viewer/components/LogTable/index.vue
- apps/kubegems/src/views/observe/monitor/app/components/Trace/Trace/index.vue
- apps/kubegems/src/views/observe/monitor/probe/components/ProbeMonitor.vue
- apps/kubegems/src/views/resource/appmanifest/components/AppResourceFileList/index.vue
- apps/kubegems/src/views/resource/components/common/Terminal/FileDownloader.vue
- apps/kubegems/src/views/resource/components/common/Terminal/FileUploader.vue
- apps/kubegems/src/views/resource/components/common/Terminal/FileViewer.vue
- apps/kubegems/src/views/resource/components/common/Terminal/index.vue
- apps/kubegems/src/views/resource/components/i18n/en.json
- apps/kubegems/src/views/resource/components/i18n/ja.json
- apps/kubegems/src/views/resource/components/i18n/zh-Hans.json
- apps/kubegems/src/views/resource/components/i18n/zh-Hant.json
- apps/kubegems/src/views/resource/node/index.vue
- apps/kubegems/src/views/setting/prometheus/components/ScopeResourceTree.vue
- packages/components/baseComponents/BaseDialog.vue
- packages/components/baseComponents/BaseFullScreenDialog.vue
- packages/extension/i18n/en.json
- packages/extension/i18n/ja.json
- packages/extension/i18n/zh-Hans.json
- packages/extension/i18n/zh-Hant.json
- packages/libs/utils/helpers.ts
Fixes #
Reference to #
```release-note
NONE
```
> feat: :sparkles: support file tree from terminal

- CHANGELOG.md
- apps/kubegems/src/assets/styles/vuetify_overwrite.scss
- apps/kubegems/src/views/resource/components/common/Terminal/FileUploader.vue
- apps/kubegems/src/views/resource/components/common/Terminal/FileViewer.vue
- apps/kubegems/src/views/resource/components/common/Terminal/index.vue
- apps/kubegems/src/views/resource/pod/components/ContainerItems.vue
- packages/extension/i18n/en.json
- packages/extension/i18n/ja.json
- packages/extension/i18n/zh-Hans.json
- packages/extension/i18n/zh-Hant.json
- pnpm-lock.yaml
Fixes #
Reference to #
```release-note
NONE
```
> perf: :zap: optimization file viewer

- CHANGELOG.md
- apps/kubegems/src/views/microservice/service/index.vue
- apps/kubegems/src/views/microservice/workload/index.vue
- apps/kubegems/src/views/observe/log/config/flow/components/ResourceInfo.vue
- apps/kubegems/src/views/observe/log/config/flow/index.vue
- apps/kubegems/src/views/observe/log/i18n/en.json
- apps/kubegems/src/views/observe/log/i18n/ja.json
- apps/kubegems/src/views/observe/log/i18n/zh-Hans.json
- apps/kubegems/src/views/observe/log/i18n/zh-Hant.json
- apps/kubegems/src/views/resource/components/metadata/Metadata/index.vue
- apps/kubegems/src/views/resource/configmap/components/AddConfigMap.vue
- apps/kubegems/src/views/resource/configmap/components/UpdateConfigMap.vue
- apps/kubegems/src/views/resource/node/components/Taint/index.vue
- apps/kubegems/src/views/resource/node/index.vue
- packages/components/baseComponents/BaseCollapseChips.vue
Fixes #
Reference to #
```release-note
NONE
```
> style: :lipstick: update collapse chips style

- CHANGELOG.md
- apps/kubegems/src/request.ts
- apps/kubegems/src/views/resource/cluster/components/ClusterBaseForm/ValidateKubeConfig.vue
- apps/kubegems/src/views/setting/model_registry/components/ModelList/index.vue
- apps/kubegems/src/views/setting/model_registry/index.vue
- apps/observability/src/layouts/header/Header.vue
- apps/servicemesh/src/layouts/header/Header.vue
- packages/api/hooks/ai_model.ts
- packages/components/baseComponents/BaseDatePicker.vue
- packages/extension/i18n/en.json
- packages/extension/i18n/ja.json
- packages/extension/i18n/zh-Hans.json
- packages/extension/i18n/zh-Hant.json
- pnpm-lock.yaml
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix admin model list api error bug

- packages/extension/ruler.ts
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix regexp NFA bug

- .github/workflows/build.yml
- .gitignore
- apps/kubegems/arm64.Dockerfile
- packages/extension/i18n/zh-Hans.json
Fixes #
Reference to #
```release-note
NONE
```
> support arm

- packages/extension/ruler.ts
Fixes #
Reference to #
```release-note
NONE
```
> fix: :bug: fix regex trigger error bug

- apps/kubegems/src/request.ts
- apps/observability/src/request.ts
- apps/servicemesh/src/request.ts
- packages/extension/store/vuex/index.ts
Fixes #
Reference to #
```release-note
NONE
```
> style: :zap: fix theme changed bug

- apps/kubegems/src/views/resource/workload/components/WorkloadBaseForm/ContainerImage/ContainerImageSelect.vue
- apps/kubegems/src/views/resource/workload/components/WorkloadBaseForm/ContainerImage/index.vue
Fixes #
Reference to #
```release-note
NONE
```
> 🐛 fix cat not list image registry for appmanifest bug

- apps/kubegems/.eslintrc.js
- apps/kubegems/package.json
- apps/kubegems/src/views/resource/ingress/components/IngressBaseForm/index.vue
- apps/kubegems/src/views/resource/workload/components/WorkloadBaseForm/DeployPolicy.vue
Fixes #
Reference to #
```release-note
NONE
```
> :zap: fix deploy policy bug and create ingress bug

- apps/observability/src/views/observe/monitor/config/prometheusrule/components/CopyPrometheusRule.vue
- apps/observability/src/views/observe/monitor/dashboard/components/DashboardBaseForm.vue
- apps/observability/src/views/observe/monitor/dashboard/components/VariableSelect.vue
Fixes #
Reference to #
```release-note
NONE
```
> perf: ⚡ optimization observability from components
